### ISSUE TITLE
Cannot create DRM context without X server running.

### ISSUE THREAD

**Issue by Omnomios** [SFML/SFML#2946]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

When I attempt to run any of the example programs I get the message:
`
DRM device used: 0
DRM device used: 1
DRM using the current mode
DRM Mode used: 3840x2160@60
Failed to set mode: Invalid argument
`
I've tried with different modes using SFML_DRM_MODE and selecting different devices with SFML_DRM_DEVICE but the outcome is the same no matter the combination.

If I start the same program with `startx` then it doesn't give an error but there is no output on the display.

I've confirmed the GPU can output the selected mode with `glmark2` and with a vanilla build of SFML. It's only the DRM build that won't start.

### Your Environment

- OS / distro / window manager: 
Linux 6.1.25 Debian Bookworm
- SFML version: 
2.6.1
- Compiler / toolchain: 
GCC version 12.2.0 - aarch64-linux-gnu
- Special compiler / CMake flags:
SFML_USE_DRM SFML_BUILD_EXAMPLES

### Steps to reproduce

1. Download SFML 2.6.1 source
2. Build with CMAKE flag SFML_USE_DRM and SFML_BUILD_EXAMPLES
3. Run `./examples/opengl/opengl` without an X server running

### Expected behavior

Connected display should show a spinning cube on a jungle background

### Actual behavior

Program wont start with the error message "Failed to set mode: Invalid argument"

**Comment by Omnomios** [comment]
Further investigation I found this in the DRM logs when I switched it to debug logging

```
Apr 14 12:47:22 localhost kernel: [drm:drm_helper_probe_single_connector_modes] [CONNECTOR:450:DP-1] probed modes :
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "3840x2160": 60 533250 3840 3888 3920 4000 2160 2214 2219 2222 0x48 0x9
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "3840x2160": 30 266640 3840 3848 3992 4000 2160 2214 2219 2222 0x40 0x9
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "2560x1440": 60 241500 2560 2608 2640 2720 1440 1443 1448 1481 0x40 0x9
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1920x1080": 60 148500 1920 2008 2052 2200 1080 1084 1089 1125 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1920x1080": 60 148500 1920 2008 2052 2200 1080 1084 1089 1125 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1920x1080": 60 148352 1920 2008 2052 2200 1080 1084 1089 1125 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1600x900": 60 108000 1600 1624 1704 1800 900 901 904 1000 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1280x1024": 60 108000 1280 1328 1440 1688 1024 1025 1028 1066 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1280x800": 60 83500 1280 1352 1480 1680 800 803 809 831 0x40 0x6
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1280x720": 60 74250 1280 1390 1430 1650 720 725 730 750 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1280x720": 60 74250 1280 1390 1430 1650 720 725 730 750 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1280x720": 60 74176 1280 1390 1430 1650 720 725 730 750 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "1024x768": 60 65000 1024 1048 1184 1344 768 771 777 806 0x40 0xa
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "800x600": 60 40000 800 840 968 1056 600 601 605 628 0x40 0x5
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "720x480": 60 27027 720 736 798 858 480 489 495 525 0x40 0xa
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "720x480": 60 27000 720 736 798 858 480 489 495 525 0x40 0xa
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "640x480": 60 25200 640 656 752 800 480 490 492 525 0x40 0xa
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "640x480": 60 25175 640 656 752 800 480 490 492 525 0x40 0xa
Apr 14 12:47:22 localhost kernel: [drm:drm_mode_debug_printmodeline] Modeline "640x480": 60 25175 640 656 752 800 480 490 492 525 0x40 0xa
Apr 14 12:47:23 localhost kernel: [drm:rockchip_gem_get_pages.constprop.0] bank_bit_first = 0xd, bank_bit_mask = 0x7
Apr 14 12:47:23 localhost kernel: [drm:rockchip_gem_get_pages.constprop.0] rockchip_gem_get_pages, 222, end = 4, n_pages = 4
Apr 14 12:47:23 localhost kernel: [drm:rockchip_gem_get_pages.constprop.0] bank_bit_first = 0xd, bank_bit_mask = 0x7
Apr 14 12:47:23 localhost kernel: [drm:rockchip_gem_get_pages.constprop.0] rockchip_gem_get_pages, 222, end = 520, n_pages = 520
Apr 14 12:47:23 localhost kernel: rockchip-drm display-subsystem: [drm:drm_mode_addfb2] [FB:464]
Apr 14 12:47:23 localhost kernel: [drm:drm_mode_setcrtc] [CRTC:157:video_port2]
Apr 14 12:47:23 localhost kernel: [drm:drm_mode_setcrtc] Invalid pixel format AR24 little-endian (0x34325241), modifier 0xffffffffffffff
```

**Comment by binary1248** [comment]
The DRM implementation was written/ported by @mickelson, @oomek and @substring. Maybe they can look into this.

**Comment by fxlevy** [comment]
Hello, I see that you consider this issue as solved. But I still have the issue.
First, I don't know how to build from this pull request, so I used the [drm_init](https://github.com/mickelson/SFML/tree/drm_init) branch from [mickelson](https://github.com/mickelson) SFML repo.
If anyone could explain me how to build from this pull request, it would be great.

For those tests, I use a VM (system type x86_64) executed from my Mac Intel using the latest Debian Bookworm updates wittout x.

Compiling with the Debug flag using the following Cmake options:

`-DSFML_OPENGL_ES=TRUE -DSFML_USE_DRM=TRUE -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_BUILD_TYPE=DEBUG`

I have the following result for the opengl example program.

```
myuser@mydebian:~$ cd rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl/
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl$ ./opengl-d 
DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
DRM Mode used: 800x600@60
Failed to set mode: Invalid argument
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl$ 

```

**Comment by substring** [comment]
Are you in the video group ? Does your VM video adapter support OpenGL ?

**Comment by fxlevy** [comment]
@substring , my test user is a member of the video group

```
myuser@mydebian:~$ sudo groups myuser
myuser : myuser cdrom floppy sudo audio dip video plugdev users input netdev bluetooth

```
 
Yes, my video is supporrting Open GL. I have a test program for SDL2 which mentions it:

```
SDL linrary used : 2.30.7
Testing SDL video drivers available:
 KMSDRM
 offscreen
 dummy
 evdev

SDL video driver selected : KMSDRM

Display size
-----------------------------
SDL_DisplayMode Width  : 1024
SDL_DisplayMode Height : 768

SDL video reenderer selected : opengles2

```

And the kmscibe program is also working fine.

```
Using display 0x55757a2356a0 with EGL version 1.4
===================================
EGL information:
  version: "1.4"
  vendor: "Mesa Project"
  client extensions: "EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless"
  display extensions: "EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display "
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 3.0 Mesa 22.3.6"
  shading language version: "OpenGL ES GLSL ES 3.00"
  vendor: "Mesa/X.org"
  renderer: "virgl (AMD Radeon Pro 5500M OpenGL Engine (Compat))"

```

**Comment by substring** [comment]
Which branch are you using ? I've never tried master, just the 2.6.x

**Comment by eXpl0it3r** [comment]
Building the branch is essentially equivalent to building the PR.

**Comment by substring** [comment]
> But I would say that I am not suprised because it deosn't currently includes the correction proposed by michelson. And I don't know how to build the pull request. That's why I cloned from michelson repo.

No, although the DRM implementation of SFML was heavily based on mickelson's work, we had to correct a number of things. So, in order to work on the same codebase, let's stick to the 2.6.x branch 😉 DRM was merged in 2.6.x in 2022

**Comment by eXpl0it3r** [comment]
@substring I think @fxlevy means the open PR #3136, which is based on mickelson's drm_init branch, i.e. a branch dedicated to fix the problem mentioned in this issue.

**Comment by fxlevy** [comment]
That's exactly what I mean @substring . :)

**Comment by mickelson** [comment]
> I used the [drm_init](https://github.com/mickelson/SFML/tree/drm_init) branch from [mickelson](https://github.com/mickelson). If I build from 2.6.x branch of the SFML repo, I have the same result.
> 
> ```
> DRM device used: 0
> DRM using the current mode
> DRM Mode used: 1024x768@60
> Failed to set mode: Invalid argument
> Aborted
> ```
> 
> But I would say that I am not suprised because it deosn't currently includes the correction proposed by michelson. And I don't know how to build the pull request. That's why I cloned from michelson repo.

@fxlevy could you double check whether you were actually using the drm_init version of sfml when you got these results?  The reason I ask is I'm pretty sure the drm_init branch changed the debug output a couple places.  The "DRM device used" line should give the full name of the drm device now and not just an index, and the "DRM using the current mode" message was removed....

**Comment by mickelson** [comment]
@fxlevy what happens if you run the drm_init version with the environment variable SFML_DRM_MODE=1024x768

?

**Comment by fxlevy** [comment]
@mickelson , result is the same.
Here ere the commands i executed:

```
myuser@mydebian:~$ export SFML_DRM_MODE=1024x768
myuser@mydebian:~$ echo $SFML_DRM_MODE
1024x768
myuser@mydebian:~$ cd rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl/
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl$ ./opengl-d 
DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
DRM Mode used: 1024x768@60
Failed to set mode: Invalid argument
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl$ 

```

As a complementary information: Each time I have the error `Failed to set mode: Invalid argument` I loose my keyboard and I have to restart the VM.

**Comment by fxlevy** [comment]
Hello I don't if that could help but I made I created a btrand new VM with the latest Bookworm version 12.6 and directly made a compilation of SFML with the official repo 2.6.1 and drm_init from @mickelson .
I used the same flags for the cmake command:
`-DSFML_OPENGL_ES=TRUE -DSFML_USE_DRM=TRUE -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_BUILD_TYPE=DEBUG
`
In both cases I have the same result but there is also an access denied errror :

```
DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
Error opening /dev/input/event0: Permission denied
Error opening /dev/input/event1: Permission denied
Error opening /dev/input/event2: Permission denied
Error opening /dev/input/event3: Permission denied
Error opening /dev/input/event4: Permission denied
Error opening /dev/input/event5: Permission denied
Error opening /dev/input/event6: Permission denied
DRM Mode used: 800x600@60
Failed to set mode: Invalid argument

```

If I execute the example with a sudo command the permission error dissapear, my keyboard is still usable but the resultat is the same. If i add my user to the the `input`the pemission error disappear, my keybaord is unusable and the result is still the same.

**Comment by fxlevy** [comment]
Hello, I proceeded to additional tests. I have a Pi 5 with NVME 1Tb . I made a fresh install of the Raspi OS light on it. I built the 2.6.x branch with the same cmake options. 

```
# cmake options = '-DSFML_OPENGL_ES=TRUE -DSFML_USE_DRM=TRUE -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_BUILD_TYPE=DEBUG'
```

And for the make
# Arch Options  : -march=armv8.2-a+crc+simd -mcpu=cortex-a76 -mcpu=cortex-a76 
# Make Options  : 

The result is different but I still have an issue:

```
pi@pi5host:~/rpi4mame_build/sources/SFML/SFML-2.6.x/examples/opengl $ ./opengl-d 
DRM device used: 0
DRM device used: 1
DRM using the current mode
DRM Mode used: 1920x1080@60
An internal EGL call failed in DRMContext.cpp (747) : 
Expression:
   m_context = eglCreateContext(m_display, m_config, toShared, contextVersion)
Error description:
   EGL_BAD_ALLOC
   EGL failed to allocate resources for the requested operation

Failed to create EGL context
An internal EGL call failed in DRMContext.cpp (747) : 
Expression:
   m_context = eglCreateContext(m_display, m_config, toShared, contextVersion)
Error description:
   EGL_BAD_ALLOC
   EGL failed to allocate resources for the requested operation

Failed to create EGL context
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 0.0 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Failed to activate the window's context
Failed to activate the window's context
Segmentation fault
```

Using the drm_init branch of mickelson/SFML repo generates the same issue.

```
pi@pi5host:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl $ ./opengl-d 
DRM device used: /dev/dri/card1
DRM Mode used: 1920x1080@60
An internal EGL call failed in DRMContext.cpp (753) : 
Expression:
   m_context = eglCreateContext(m_display, m_config, toShared, contextVersion)
Error description:
   EGL_BAD_ALLOC
   EGL failed to allocate resources for the requested operation

Failed to create EGL context
DRM Mode used: 800x600@60
An internal EGL call failed in DRMContext.cpp (753) : 
Expression:
   m_context = eglCreateContext(m_display, m_config, toShared, contextVersion)
Error description:
   EGL_BAD_ALLOC
   EGL failed to allocate resources for the requested operation

Failed to create EGL context
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Created: version = 0.0 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false ; sRGB = false
Failed to activate the window's context
Failed to activate the window's context
Segmentation fault
pi@pi5host:~/rpi4mame_build/sources/SFML/SFML-drm_init/examples/opengl $ 
```

But the 'kmscube' works fine.

**Comment by mickelson** [comment]
Hi fxlevy, 

I just pushed a new update to my drm_init pull request with some changes to the EGL settings and some additional logging that *might* give a hit as to the issue you're running into. Please let me know if it changes anything for you... thanks!
Andrew

**Comment by natxopedreira** [comment]
I just tested this on a cm4 board running raspbian 64 bit and works perfect.

Compile the 2.6.x branch with SFML_USE_DRM flag

**Comment by Ronbinn** [comment]
Coming from here
https://github.com/oomek/attractplus/issues/82#issue-2699489396

I'm trying to install attractplus in a regular 64 bit pc (not an arm board). I'm using Debian Bookworm. It seems to be a SMFL bug. So...

I've cloned mickelson's repo
`git clone -b drm_init https://github.com/mickelson/SFML`

Set cmake options
`make -DSFML_USE_DRM=TRUE -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_BUILD_TYPE=DEBUG .`

Compiled with no errors. 

Then I try to launch the opengl example
`export SFML_DRM_MODE=1024x768 &&
cd examples/opengl &&
./opengl-d`

> DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
DRM Mode used: 1024x768@60
Failed to set mode: Invalid argument
Aborted

**Comment by oomek** [comment]
The same error message pops up in DRM when I create a new sf::Context for in a separate thread used for asynchronous texture loading on other platforms. And no, I have no idea how to fix it unfortunately.

**Comment by fxlevy** [comment]
> I'm trying to install attractplus in a regular 64 bit pc (not an arm board). I'm using Debian Bookworm. It seems to be a SMFL bug. So...

Hello, The issue I explained is exactly the same as you expose it @Ronbinn , except that I compile and test on a VM running on a MacBook Pro Intel. So, the Bookworm system architecture of the VM is X86_64. On an ARM architcutre there is no issue (I compiled and test on a Raspberry Pi 5 whith the latest Bookworm realease install). So, it seems that this issue happens on Intel architecture only (To be confirmed, I'm not an expert).

**Comment by oomek** [comment]
Please try to set `EGL_CONTEXT_CLIENT_VERSION, 2` It worked for me.
https://github.com/SFML/SFML/blob/03812a545d4ce7cfadd5fa0fb7d98053ef38982b/src/SFML/Window/DRM/DRMContext.cpp#L702

**Comment by Omnomios** [comment]
Thought I would swing by and give an update.
I pulled down and built the 2.6.x branch on a Rock5B board and it worked as expected without issue.

The original problem this ticket raised has been resolved, so I assume this can be closed now?

**Comment by fxlevy** [comment]
@Omnomios , you're right. It seems that it works on a Cortex CPU device (eg Raspberry Pi 5). But on my virtual machine running debian intel based X86-64 version, the issue is still there.

@oomek , I applied your modification, and now I have multiple error messages.

Before your proposed code modification:

```
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-3.0.0/examples/opengl$ ./opengl-d 
DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
DRM Mode used: 800x600@60
Failed to set mode: Invalid argument
Aborted

```

After code modification

```
myuser@mydebian:~/rpi4mame_build/sources/SFML/SFML-3.0.0/examples/opengl$ ./opengl-d 
DRM device used: /dev/dri/card0
DRM Mode used: 1024x768@60
DRM Mode used: 800x600@60
OpenGL error (1280) detected during glCheck call
An internal OpenGL call failed in "Texture.cpp"(965).
Expression:
   glMatrixMode(GL_TEXTURE)
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

...

Failed to set mode: Invalid argument
Aborted

```

As a reminder, the `kmscube`command is working with the following outputs:

```
Using display 0x55cae47d72a0 with EGL version 1.4
===================================
EGL information:
  version: "1.4"
  vendor: "Mesa Project"
  client extensions: "EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless"
  display extensions: "EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display "
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 3.0 Mesa 22.3.6"
  shading language version: "OpenGL ES GLSL ES 3.00"
  vendor: "Mesa/X.org"
  renderer: "virgl (AMD Radeon Pro 5500M OpenGL Engine (Compat))"
  extensions: "GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_NV_pack_subimage GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_debug_label GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_integer_mix GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_NV_shader_noperspective_interpolation GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_multisample_interpolation GL_OES_texture_border_clamp GL_EXT_blend_func_extended GL_EXT_float_blend GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_color_buffer_half_float GL_EXT_texture_compression_bptc GL_EXT_texture_mirror_clamp_to_edge GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_MESA_framebuffer_flip_y GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra "
===================================

```

Meaning that opengl is working.
