### ISSUE TITLE
Graphic glitch when displaying text containing non-breaking spaces

### ISSUE THREAD

**Issue by AerunDev** [SFML/SFML#2985]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

We're using SFML with an open-source community to manage the display of our games.
We were previously on version 2.5.0, and since we've upgraded to 2.6.1, we've noticed a graphical issue when displaying text with non-breaking spaces. This is problematic for some languages like French, which uses them to manage word spacing.

We've tested several fonts, and the same issue persists in 2.5.1 and 2.6.1, but not in 2.5.0. It seems that the transition from 2.5.0 to 2.5.1 introduced this problem.

I'm attaching a screenshot:
![2-6-1-tuffy-graphic-issue](https://github.com/SFML/SFML/assets/20935418/153008f3-58b8-42b8-9bf0-120a12702240)

And a version with the window enlarged for better observation of the issue:
![2-6-1-tuffy-graphic-issue-zoomed](https://github.com/SFML/SFML/assets/20935418/02815d71-e6a5-43a0-9d81-5e9c7526ebbb)

And a version with another font:
![Capture d'écran 2024-05-07 184401](https://github.com/SFML/SFML/assets/20935418/dde862e4-26b3-4895-835f-2ba5146f3285)

### Your Environment

- OS / distro / window manager: **Windows 11 x64** (but tested on Windows 10 too)**
- SFML version: **2.6.1** (the issue is also verifiable in the 2.5.1 version)
- Compiler / toolchain: **Visual Studio 2022**
- Special compiler / CMake flags: **32 bits - x86 Release**

### Steps to reproduce

1. Setup a 2.6.1 32 bits project (x86)
2. Add the font in the `resources/` folder
3. Run the following code using 2.6.1
4. Check if the non-breaking space is properly displayed

```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(640, 480), "SFML works!");
    sf::Font font;
    // Font from the island example of 2.6.1
    if (!font.loadFromFile("resources/tuffy.ttf"))
        return EXIT_FAILURE;

    sf::Text text;
    text.setFont(font);
    text.setString("L'utiliser sur quelle créature ?");
    text.setCharacterSize(40);
    text.setFillColor(sf::Color::Red);
    text.setStyle(sf::Text::Bold);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(text);
        window.display();
    }

    return 0;
}
```

### Expected behavior

Non-breaking spaces should be properly displayed.

### Actual behavior

Seems like a graphic glitch is displayed. If we resize the window it seems like this is a pixel, maybe due to the glyph?

**Comment by NuriYuri** [comment]
Hi, allow me to answer. Yes the glitch is the "dot" between the e of créature and the question mark.
The rendering of the question mark is not related (I guess the font he uses in example 1 & 2 does not contain U+FF1F).

The #1452 looks to be a good candidate for the regression, if I find time I'll try to build some binaries without this commit and see. (This candidate might also explain why sometimes we smooth gets randomly enabled.)

**Comment by AerunDev** [comment]
Hello @eXpl0it3r! 😄
Any update on this issue?
I've seen that SFML 3.0 will be ended soon. Do you think a fix for this issue can be included in the 3.0?
Thanks in advance.

**Comment by pw-rey** [comment]
Hello!
I took the time to build a test case of this issue on both Windows 11 and Ubuntu 22.04 with SFML 2.6.2 and with different fonts (including tutty.ttf).
I tried reverting the two main changes of #1452 as @NuriYuri suggested and it seems like the adding of the "padding" in `void addGlyphQuad` is what caused the regression.

This test was also successful on SFML 3.0.0, though another unrelated issue arose where the tutty font caused the drawing to stop at the first occurrence of a non-breaking space (which didn’t happen with another font). As it’s unrelated, I can open an issue for this if you think it’s necessary.

**Comment by AerunDev** [comment]
Hello @eXpl0it3r !
Is it possible to get an update on this issue?
Is a fix planned regarding what @pw-rey and @NuriYuri mentioned?
Has it already been fixed in 3.0? (So we know if we should update)
Should we propose a fix on our side through a PR?

Thanks a lot for your answer, it will help us resolve this problem.
Good luck, and thanks for all the work you’re doing!

**Comment by ChrisThrasher** [comment]
Nothing is explicitly planned yet. Can anyone confirm whether this bug still exists in 3.0.1? We will likely not be shipping any more meaningful fixes for the 2.x release series.

**Comment by NuriYuri** [comment]
The issue is still there in 3.0. Be careful because github eats the non breaking spaces:

<img width="1387" height="821" alt="Image" src="https://github.com/user-attachments/assets/55852676-24bb-4226-843a-796b5097a252" />

**Comment by kimci86** [comment]
As far as I can see, this is a consequence of an encoding issue. Then, something in freetype and/or Tuffy font return a big advance metric for invalid glyphs, making the rest of the string disappear out of the view.

Maybe we could make SFML behave better with invalid encoding, but in the meantime, using UTF-8 should solve the issue:

Example on SFML master branch:

```c++
#include <SFML/Graphics.hpp>

int main()
{
    auto window = sf::RenderWindow{sf::VideoMode({640, 480}), "SFML works!"};
    auto font   = sf::Font{"resources/tuffy.ttf"};

    const auto data = std::string_view{"L'utiliser sur quelle créature ?"};
    auto       text = sf::Text{font, sf::String::fromUtf8(data.begin(), data.end()), 40};
    text.setFillColor(sf::Color::Red);
    text.setStyle(sf::Text::Bold);

    while (window.isOpen())
    {
        while (const std::optional event = window.pollEvent())
        {
            if (event->is<sf::Event::Closed>())
                window.close();
        }
        window.clear();
        window.draw(text);
        window.display();
    }
}
```

<img width="668" height="546" alt="Image" src="https://github.com/user-attachments/assets/3a3b0013-20fc-4d7d-9759-3294bcfa473d" />

**Comment by NuriYuri** [comment]
Be careful, github eats non breaking spaces.

In our library we only use UTF-8 and we're indeed using that function to cast from utf-8 to utf-32.

<img width="1387" height="821" alt="Image" src="https://github.com/user-attachments/assets/7a216654-da4e-4ab3-94bd-2127f8b2bb1a" />

**Comment by kimci86** [comment]
I confirm I used a non breaking space in my example above.
I am not on windows though. Maybe the source file encoding is the problem.
Can you make sure you save your source file as UTF-8?
What if you use only ASCII characters to encode the string? like this: `"L'utiliser sur quelle cr\u00e9ature\u00a0?"`

**Comment by NuriYuri** [comment]
The file is indeed in UTF-8 and the string is saved in UTF-8 in the binary as well :)
Screenshot of the binary .data section as Windows-1252:

<img width="763" height="83" alt="Image" src="https://github.com/user-attachments/assets/c969e08b-c0d3-4841-a748-eeddc9b02e03" />

Screenshot of the binary .data section as UTF-8:

<img width="763" height="83" alt="Image" src="https://github.com/user-attachments/assets/f3b00f19-ed68-4287-9883-a25b368b8fe3" />

If I use Windows-1252 encoding I get a warning and the following result (which is way worse):

<img width="998" height="165" alt="Image" src="https://github.com/user-attachments/assets/b4ad0712-3c8a-46d0-aa20-fbc1253d0da9" />

Note: I'm on MacOS right now, but it seems the behavior is somewhat consistent between MacOS and Windows, the difference being MacOS uses UTF-8 while Windows uses UTF-16LE.

**Comment by AerunDev** [comment]
Hi @ChrisThrasher,
Any update on this issue?
I understand it may seem low priority, but for projects that use non-breaking spaces (especially in French), it has quite an impact.
Thank you so much!

**Comment by eXpl0it3r** [comment]
Given that we fixed quite a few things regarding UTF-8 handling and introduced complex text layout in 3.1, I think it makes sense to investigate this and hopefully include this with 3.1

**Comment by binary1248** [comment]
OK... so there is a lot to unpack here.

The problem that is described can be caused by multiple different issues.

1. The initial conversion from source text to `sf::String` in UTF-32 has to be correct. For this the correct function for the source encoding has to be chosen.
2. The text has to be shaped correctly respecting non-breaking spaces.
3. The chosen font has to provide metrics for non-breaking spaces.
4. If the font does not support non-breaking spaces then it will replace the glyph with the default .notdef glyph. Depending on the font this glyph can have different appearances resulting in the "Tofu" that is familiar from e.g. web browsers.
5. The .notdef glyph should provide usable metrics just as any other glyph.
6. After shaping is complete, the glyph geometry and texture is positioned according to shaper output.

Based on the original code example, I assume that the source text was encoded in ANSI (ISO 8859-1). When constructing an `sf::String` from a null-terminated C-String the encoding that is used defaults to ANSI. This is due to backwards compatibility. When decoding from a UTF-8 encoded null-terminated C-String the `::fromUtf8` function will have to be used explicitly. If the source text was encoded as UTF-8 and the default `sf::String` constructor is used it will lead to an incorrect conversion being performed.

When testing Unicode functionality, instead of relying on the source text encoding to be correct it is much simpler to just encode the bytes directly into the string literal instead of using any non-ASCII characters. This guarantees that the bytes that are passed to SFML are those that are intended.

SFML currently doesn't warn or indicate when a conversion error happens. One of a few things can happen in case something goes wrong: Invalid code sequences can be silently discarded, invalid UTF-8 code units can be simply widened to UTF-32 codepoints resulting in completely different characters in the output, conversion failure can just truncate the rest of the string starting at the point of failure. Because this isn't very user friendly, I opened #3628 to try to improve this a bit.

Now... assuming the UTF-32 is correct, it has to be processed by the text shaper in order to determine where to position each glyph. Prior to `sf::Text` being rewritten to make use of HarfBuzz for shaping, SFML implemented its own very primitive "shaping" algorithm. This algorithm only really functioned properly for ASCII and similar scripts that didn't require advanced shaping support. One of the many things that the old shaping code didn't properly support was non-breaking spaces. The only horizontal whitespace it supported was the ASCII space character, as such the non-breaking space unicode codepoint was treated as an ordinary glyph by the shaping code which caused it to expect a textured quad to be drawn at its position. The reason why the artifact described by @AerunDev only started showing up in 2.5.1 is because SFML started to add padding around the quads as can be seen when [comparing 2.5.0 and 2.5.1](https://github.com/SFML/SFML/compare/2.5.0...2.5.1#diff-22c1fd53bbab429b4a348662278b21abb1d7a063aa14b175a8f3a5451c783b6c). Trying to render an empty quad would thus result in a single pixel with the colour of the text being drawn at the position at which the glyph should have been positioned.

If the UTF-32 is not correct and a completely different glyph had to be loaded for the codepoint, it depends on whether the glyph is available in the used font. Every font has a .notdef glyph defined with ID 0 that is used as a placeholder for missing glyphs. The thing that makes the tuffy.ttf font special is that the metrics for this placeholder glyph are broken. Trying to load tuffy.ttf into FontForge causes the following warning to be output:
```
In GID 0 the advance width (32768) is greater than the stated maximum (3969)
  Subsequent errors will not be reported.
```
The reason we thought something else was broken is due to the fact that the width of the window in the example code was set to 640. Increasing it to e.g. 1000 will reveal that the characters following the non-breaking space are just shifted to the right by 640 pixels. This is the advance that the .notdef glyph in tuffy.ttf reports to the shaper. Using a font that has proper .notdef metrics would advance the drawing position by the correct amount but still have the problem of zero area geometry and thus still result in the single pixel being drawn.

The only way to fix the single pixel problem is by moving over to the new shaper and `sf::Text` implementation which correctly handle positioning even for glyphs with zero area.

In summary:
- If the source text is in the correct encoding
- And the correct `sf::String` decoding function is used for the encoding
- And a non-broken font file is used
- And the font file has metrics for non-breaking spaces
- And an SFML revision with the new HarfBuzz advanced shaping engine is used

Then the output should be what is expected.

If any one of those steps goes wrong then the output will not be what is expected.

When testing it is helpful to also state exactly which revision of SFML you are testing with (using e.g. the SHA of the commit) or stating if you are using an official tagged release. Because we don't increment the version number until the next official release, saying "SFML 3.x.y" can mean many different things and it makes it hard to determine if the issue has already been fixed in the meantime or which revision we would need to check out to reproduce what is reported.

**Comment by eXpl0it3r** [comment]
Hard to say where things went wrong, as outlined by binary1248 there are a bunch of places that could cause problems. With #3628 merged, there is a way to test invalid conversions now.

Closing this for now, if you can test all the mentioned steps and find where it fails, feel free to reopen the issue.
